// Code generated by "stringer -type=Symbol"; DO NOT EDIT.

package binance

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SymbolUnknown-0]
	_ = x[ETHBTC-1]
	_ = x[LTCBTC-2]
	_ = x[BNBBTC-3]
	_ = x[NEOBTC-4]
	_ = x[BCCBTC-5]
	_ = x[GASBTC-6]
	_ = x[HSDBTC-7]
	_ = x[MCOBTC-8]
	_ = x[WTCBTC-9]
	_ = x[LRCBTC-10]
	_ = x[QTUMBTC-11]
	_ = x[YOYOBTC-12]
	_ = x[OMGBTC-13]
	_ = x[ZRXBTC-14]
	_ = x[STRATBTC-15]
	_ = x[btcSentinel-16]
	_ = x[QTUMETH-101]
	_ = x[EOSETH-102]
	_ = x[SNTETH-103]
	_ = x[BNTETH-104]
	_ = x[BNBETH-105]
	_ = x[OAXETH-106]
	_ = x[DNTETH-107]
	_ = x[MCOETH-108]
	_ = x[ICNETH-109]
	_ = x[WTCETH-110]
	_ = x[LRCETH-111]
	_ = x[OMGETH-112]
	_ = x[ZRXETH-113]
	_ = x[STRATETH-114]
	_ = x[ethSentinel-115]
	_ = x[BTCUSDT-201]
	_ = x[ETHUSDT-202]
	_ = x[symbolSentinel-204]
}

const (
	_Symbol_name_0 = "SymbolUnknownETHBTCLTCBTCBNBBTCNEOBTCBCCBTCGASBTCHSDBTCMCOBTCWTCBTCLRCBTCQTUMBTCYOYOBTCOMGBTCZRXBTCSTRATBTCbtcSentinel"
	_Symbol_name_1 = "QTUMETHEOSETHSNTETHBNTETHBNBETHOAXETHDNTETHMCOETHICNETHWTCETHLRCETHOMGETHZRXETHSTRATETHethSentinel"
	_Symbol_name_2 = "BTCUSDTETHUSDT"
	_Symbol_name_3 = "symbolSentinel"
)

var (
	_Symbol_index_0 = [...]uint8{0, 13, 19, 25, 31, 37, 43, 49, 55, 61, 67, 73, 80, 87, 93, 99, 107, 118}
	_Symbol_index_1 = [...]uint8{0, 7, 13, 19, 25, 31, 37, 43, 49, 55, 61, 67, 73, 79, 87, 98}
	_Symbol_index_2 = [...]uint8{0, 7, 14}
)

func (i Symbol) String() string {
	switch {
	case 0 <= i && i <= 16:
		return _Symbol_name_0[_Symbol_index_0[i]:_Symbol_index_0[i+1]]
	case 101 <= i && i <= 115:
		i -= 101
		return _Symbol_name_1[_Symbol_index_1[i]:_Symbol_index_1[i+1]]
	case 201 <= i && i <= 202:
		i -= 201
		return _Symbol_name_2[_Symbol_index_2[i]:_Symbol_index_2[i+1]]
	case i == 204:
		return _Symbol_name_3
	default:
		return "Symbol(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
